package com.micro.rent.pc.entity;

import org.postgresql.geometric.PGpoint;


public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.country_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.province_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.city_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.district_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.street
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.building_no
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String buildingNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.door_plate
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String doorPlate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.address
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.point
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Object point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.zoom_level
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Object zoomLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.flag
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Boolean flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.address.plot
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String plot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.id
     *
     * @return the value of public.address.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.id
     *
     * @param id the value for public.address.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.country_id
     *
     * @return the value of public.address.country_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.country_id
     *
     * @param countryId the value for public.address.country_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setCountryId(String countryId) {
        this.countryId = countryId == null ? null : countryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.province_id
     *
     * @return the value of public.address.province_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.province_id
     *
     * @param provinceId the value for public.address.province_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.city_id
     *
     * @return the value of public.address.city_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.city_id
     *
     * @param cityId the value for public.address.city_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.district_id
     *
     * @return the value of public.address.district_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.district_id
     *
     * @param districtId the value for public.address.district_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setDistrictId(String districtId) {
        this.districtId = districtId == null ? null : districtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.street
     *
     * @return the value of public.address.street
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.street
     *
     * @param street the value for public.address.street
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.building_no
     *
     * @return the value of public.address.building_no
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getBuildingNo() {
        return buildingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.building_no
     *
     * @param buildingNo the value for public.address.building_no
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setBuildingNo(String buildingNo) {
        this.buildingNo = buildingNo == null ? null : buildingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.door_plate
     *
     * @return the value of public.address.door_plate
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getDoorPlate() {
        return doorPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.door_plate
     *
     * @param doorPlate the value for public.address.door_plate
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setDoorPlate(String doorPlate) {
        this.doorPlate = doorPlate == null ? null : doorPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.address
     *
     * @return the value of public.address.address
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.address
     *
     * @param address the value for public.address.address
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.point
     *
     * @return the value of public.address.point
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Object getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.point
     *
     * @param point the value for public.address.point
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setPoint(Object point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.zoom_level
     *
     * @return the value of public.address.zoom_level
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Object getZoomLevel() {
        return zoomLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.zoom_level
     *
     * @param zoomLevel the value for public.address.zoom_level
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setZoomLevel(Object zoomLevel) {
        this.zoomLevel = zoomLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.flag
     *
     * @return the value of public.address.flag
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.flag
     *
     * @param flag the value for public.address.flag
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.address.plot
     *
     * @return the value of public.address.plot
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getPlot() {
        return plot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.address.plot
     *
     * @param plot the value for public.address.plot
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setPlot(String plot) {
        this.plot = plot == null ? null : plot.trim();
    }
    
    public Double getX(){
    	if (this.getPoint() != null) {
    		return ((PGpoint)point).x;
    	}
    	return null;
    }
    
    public Double getY(){
    	if (this.getPoint() != null) {
    		return ((PGpoint)point).y;
    	}
    	return null;
    }
}