package com.micro.rent.pc.entity;

public class Amenity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.amenity.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.amenity.amenity_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long amenityGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.amenity.type
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Object type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.amenity.sub_type
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Object subType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.amenity.id
     *
     * @return the value of public.amenity.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.amenity.id
     *
     * @param id the value for public.amenity.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.amenity.amenity_group_id
     *
     * @return the value of public.amenity.amenity_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getAmenityGroupId() {
        return amenityGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.amenity.amenity_group_id
     *
     * @param amenityGroupId the value for public.amenity.amenity_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setAmenityGroupId(Long amenityGroupId) {
        this.amenityGroupId = amenityGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.amenity.type
     *
     * @return the value of public.amenity.type
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Object getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.amenity.type
     *
     * @param type the value for public.amenity.type
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setType(Object type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.amenity.sub_type
     *
     * @return the value of public.amenity.sub_type
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Object getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.amenity.sub_type
     *
     * @param subType the value for public.amenity.sub_type
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setSubType(Object subType) {
        this.subType = subType;
    }
}