package com.micro.rent.pc.entity;

public class Branch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.branch.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.branch.name
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.branch.brand_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.branch.address_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.branch.property_type
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Object propertyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.branch.description
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.branch.flag
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Boolean flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.branch.rank_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long rankGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.branch.tagline
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String tagline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.branch.amenity_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long amenityGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.branch.id
     *
     * @return the value of public.branch.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.branch.id
     *
     * @param id the value for public.branch.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.branch.name
     *
     * @return the value of public.branch.name
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.branch.name
     *
     * @param name the value for public.branch.name
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.branch.brand_id
     *
     * @return the value of public.branch.brand_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.branch.brand_id
     *
     * @param brandId the value for public.branch.brand_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.branch.address_id
     *
     * @return the value of public.branch.address_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.branch.address_id
     *
     * @param addressId the value for public.branch.address_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.branch.property_type
     *
     * @return the value of public.branch.property_type
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Object getPropertyType() {
        return propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.branch.property_type
     *
     * @param propertyType the value for public.branch.property_type
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setPropertyType(Object propertyType) {
        this.propertyType = propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.branch.description
     *
     * @return the value of public.branch.description
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.branch.description
     *
     * @param description the value for public.branch.description
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.branch.flag
     *
     * @return the value of public.branch.flag
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.branch.flag
     *
     * @param flag the value for public.branch.flag
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.branch.rank_group_id
     *
     * @return the value of public.branch.rank_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getRankGroupId() {
        return rankGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.branch.rank_group_id
     *
     * @param rankGroupId the value for public.branch.rank_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setRankGroupId(Long rankGroupId) {
        this.rankGroupId = rankGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.branch.tagline
     *
     * @return the value of public.branch.tagline
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getTagline() {
        return tagline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.branch.tagline
     *
     * @param tagline the value for public.branch.tagline
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setTagline(String tagline) {
        this.tagline = tagline == null ? null : tagline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.branch.amenity_group_id
     *
     * @return the value of public.branch.amenity_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getAmenityGroupId() {
        return amenityGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.branch.amenity_group_id
     *
     * @param amenityGroupId the value for public.branch.amenity_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setAmenityGroupId(Long amenityGroupId) {
        this.amenityGroupId = amenityGroupId;
    }
}