package com.micro.rent.pc.entity;

public class Contact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contact.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contact.name
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contact.phone
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contact.house_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contact.branch_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contact.project_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.contact.brand_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    private Long brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contact.id
     *
     * @return the value of public.contact.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contact.id
     *
     * @param id the value for public.contact.id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contact.name
     *
     * @return the value of public.contact.name
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contact.name
     *
     * @param name the value for public.contact.name
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contact.phone
     *
     * @return the value of public.contact.phone
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contact.phone
     *
     * @param phone the value for public.contact.phone
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contact.house_id
     *
     * @return the value of public.contact.house_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contact.house_id
     *
     * @param houseId the value for public.contact.house_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setHouseId(Long houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contact.branch_id
     *
     * @return the value of public.contact.branch_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contact.branch_id
     *
     * @param branchId the value for public.contact.branch_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contact.project_id
     *
     * @return the value of public.contact.project_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contact.project_id
     *
     * @param projectId the value for public.contact.project_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.contact.brand_id
     *
     * @return the value of public.contact.brand_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.contact.brand_id
     *
     * @param brandId the value for public.contact.brand_id
     *
     * @mbggenerated Sun Jan 25 12:43:21 CST 2015
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }
}