package com.micro.rent.pc.entity;

public class FeeGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fee_group.id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fee_group.name
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fee_group.description
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fee_group.flag
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Boolean flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fee_group.id
     *
     * @return the value of public.fee_group.id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fee_group.id
     *
     * @param id the value for public.fee_group.id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fee_group.name
     *
     * @return the value of public.fee_group.name
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fee_group.name
     *
     * @param name the value for public.fee_group.name
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fee_group.description
     *
     * @return the value of public.fee_group.description
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fee_group.description
     *
     * @param description the value for public.fee_group.description
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fee_group.flag
     *
     * @return the value of public.fee_group.flag
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fee_group.flag
     *
     * @param flag the value for public.fee_group.flag
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }
}