package com.micro.rent.pc.entity;

public class House2community {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.house2community.id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.house2community.house_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Long houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.house2community.branch_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.house2community.project_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.house2community.community_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Long communityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.house2community.rank_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Long rankGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.house2community.flag
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Boolean flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.house2community.id
     *
     * @return the value of public.house2community.id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.house2community.id
     *
     * @param id the value for public.house2community.id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.house2community.house_id
     *
     * @return the value of public.house2community.house_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Long getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.house2community.house_id
     *
     * @param houseId the value for public.house2community.house_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setHouseId(Long houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.house2community.branch_id
     *
     * @return the value of public.house2community.branch_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.house2community.branch_id
     *
     * @param branchId the value for public.house2community.branch_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.house2community.project_id
     *
     * @return the value of public.house2community.project_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.house2community.project_id
     *
     * @param projectId the value for public.house2community.project_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.house2community.community_id
     *
     * @return the value of public.house2community.community_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Long getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.house2community.community_id
     *
     * @param communityId the value for public.house2community.community_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setCommunityId(Long communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.house2community.rank_group_id
     *
     * @return the value of public.house2community.rank_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Long getRankGroupId() {
        return rankGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.house2community.rank_group_id
     *
     * @param rankGroupId the value for public.house2community.rank_group_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setRankGroupId(Long rankGroupId) {
        this.rankGroupId = rankGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.house2community.flag
     *
     * @return the value of public.house2community.flag
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.house2community.flag
     *
     * @param flag the value for public.house2community.flag
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }
}