package com.micro.rent.pc.entity;

public class Houselayout2pic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.houselayout2pic.id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.houselayout2pic.branch_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.houselayout2pic.project_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.houselayout2pic.layout
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Object layout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.houselayout2pic.pic_path
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.houselayout2pic.priority
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    private Integer priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.houselayout2pic.id
     *
     * @return the value of public.houselayout2pic.id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.houselayout2pic.id
     *
     * @param id the value for public.houselayout2pic.id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.houselayout2pic.branch_id
     *
     * @return the value of public.houselayout2pic.branch_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.houselayout2pic.branch_id
     *
     * @param branchId the value for public.houselayout2pic.branch_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.houselayout2pic.project_id
     *
     * @return the value of public.houselayout2pic.project_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.houselayout2pic.project_id
     *
     * @param projectId the value for public.houselayout2pic.project_id
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.houselayout2pic.layout
     *
     * @return the value of public.houselayout2pic.layout
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Object getLayout() {
        return layout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.houselayout2pic.layout
     *
     * @param layout the value for public.houselayout2pic.layout
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setLayout(Object layout) {
        this.layout = layout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.houselayout2pic.pic_path
     *
     * @return the value of public.houselayout2pic.pic_path
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.houselayout2pic.pic_path
     *
     * @param picPath the value for public.houselayout2pic.pic_path
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.houselayout2pic.priority
     *
     * @return the value of public.houselayout2pic.priority
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.houselayout2pic.priority
     *
     * @param priority the value for public.houselayout2pic.priority
     *
     * @mbggenerated Sun Jan 25 12:43:22 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}